# Book settings
title: ChrisJallaine's Deep Learning Portfolio
author: Chris Jallaine
logo: logo1.gif 

# Turn off notebook execution
execution:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/chrisjallaine/dl-portfolio.git
  path_to_book: docs   # Changed from mybook to docs
  branch: main  

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# Parse markdown files with myst extensions
parse:
  myst_enable_extensions:
    - html_image
    - colon_fence